"use client";

import Link from "next/link";
import { useLanguage } from "./LanguageProvider";

type Kind = "delivery" | "returns";
type Policy = { eyebrow: string; title: string; intro: string; updated: string; sections: Array<{ title: string; paragraphs: string[] }> };

const policies: Record<"uz" | "ru" | "en" | "ja", Record<Kind, Policy>> = {
  uz: {
    delivery: { eyebrow: "MIJOZLAR UCHUN", title: "Yetkazib berish va to‘lov", intro: "Ushbu hujjat SIREN onlayn do‘konida buyurtma berish, to‘lash va yetkazib berishning asosiy tartibini belgilaydi.", updated: "Oxirgi yangilanish: {{POLICY_UPDATED_AT}}", sections: [
      { title: "1. Sotuvchi ma’lumotlari", paragraphs: ["Sotuvchi: {{LEGAL_ENTITY_NAME}}. STIR/INN: {{TAX_ID}}. Yuridik manzil: {{LEGAL_ADDRESS}}.", "Mijoz savollar, buyurtma holati va murojaatlar bo‘yicha {{SUPPORT_EMAIL}} yoki {{SUPPORT_PHONE}} orqali bog‘lanishi mumkin."] },
      { title: "2. Buyurtmani rasmiylashtirish", paragraphs: ["Mijoz mahsulot, rang, razmer va yetkazib berish manzilini tanlaydi. Buyurtma yuborilishidan oldin mahsulotlar, chegirma va yetkazib berish qiymati ko‘rsatiladi.", "Buyurtma qabul qilingani haqida xabar yuborilishi buyurtma avtomatik tasdiqlandi degani emas. Zaxira, manzil yoki narxdagi texnik xatolik aniqlansa, sotuvchi mijoz bilan bog‘lanadi."] },
      { title: "3. To‘lov", paragraphs: ["To‘lov Payme orqali amalga oshirilishi rejalashtirilgan. Mijoz mahsulot narxi va yetkazib berish qiymatini bitta to‘lovda amalga oshiradi.", "Yetkazib berish xizmatining qiymati tanlangan manzil, buyurtma hajmi va {{DELIVERY_PROVIDER_NAME}} tarifi asosida checkout sahifasida ko‘rsatiladi. To‘lov muvaffaqiyatli yakunlanmaguncha buyurtma to‘langan deb hisoblanmaydi.", "To‘lov bo‘yicha elektron chek va buyurtma ma’lumotlari mijozga ko‘rsatiladi. Payme integratsiyasi ishga tushirilmaguncha ushbu sahifa faqat loyiha shartlari draftidir."] },
      { title: "4. Yetkazib berish", paragraphs: ["Yetkazib berish {{DELIVERY_PROVIDER_NAME}} orqali amalga oshiriladi. Yetkazib berish hududi, taxminiy muddat va qiymat buyurtmani rasmiylashtirishda aniqlashtiriladi.", "Mijoz to‘liq va to‘g‘ri aloqa ma’lumoti hamda manzilni kiritishi kerak. Noto‘g‘ri manzil yoki qayta yetkazib berish bilan bog‘liq qo‘shimcha xarajatlar mijoz zimmasida bo‘lishi mumkin."] },
      { title: "5. Qabul qilish va murojaat", paragraphs: ["Buyurtmani qabul qilganda qadoqning tashqi holatini tekshirish tavsiya qilinadi. Shikastlanish yoki mahsulot mos kelmasligi aniqlansa, foto/video dalil bilan imkon qadar tezroq {{SUPPORT_EMAIL}} ga murojaat qiling.", "Qaytarish va almashtirish bo‘yicha batafsil tartib alohida “Almashtirish va qaytarish” sahifasida beriladi."] },
    ] },
    returns: { eyebrow: "MIJOZLAR UCHUN", title: "Almashtirish va qaytarish", intro: "Ushbu hujjat kiyim-kechak mahsulotlari uchun qaytarish, almashtirish va da’volarni ko‘rib chiqishning dastlabki tartibini belgilaydi.", updated: "Oxirgi yangilanish: {{POLICY_UPDATED_AT}}", sections: [
      { title: "1. Murojaat qilish", paragraphs: ["Murojaat muddati: {{RETURN_PERIOD}}. Mijoz buyurtma raqami, mahsulot nomi, muammo tavsifi va foto/video bilan {{SUPPORT_EMAIL}} ga yozishi kerak.", "Qaytarish manzili: {{RETURN_ADDRESS}}. Mahsulotni yuborishdan avval SIREN jamoasidan qaytarish bo‘yicha ko‘rsatma oling."] },
      { title: "2. Sifat nuqsoni yoki noto‘g‘ri jo‘natma", paragraphs: ["Agar zavod nuqsoni, komplektatsiya xatosi yoki buyurtmaga mos kelmaslik SIREN tomonidan tasdiqlansa, mahsulotni omborga qaytarib olib kelish xarajatini SIREN o‘z hisobidan tashkil qiladi yoki qoplaydi. Mijoz mahsulotni yuborishdan oldin qaytarish yo‘riqnomasini olishi kerak.", "Mahsulot omborga kelgach tekshiruvdan o‘tadi. Nuqson tasdiqlansa, mijoz mahsulot qiymatini qaytarish, almashtirish yoki qonunda nazarda tutilgan boshqa yechimni tanlashi mumkin. Buyurtmadagi dastlabki yetkazib berish haqi avtomatik qaytarilmaydi; biroq qonunda yoki aniq holatdagi zarar uchun qoplash majburiy bo‘lsa, qonun talabi ustun turadi."] },
      { title: "3. Xaridor xohishiga ko‘ra qaytarish", paragraphs: ["Razmer, rang, fason mos kelmagani yoki mahsulot yoqmagani sababli qaytarishda mijoz qaytarish yetkazib berishining to‘liq qiymatini o‘zi to‘laydi. SIREN bunday holatda jo‘natma uchun oldindan to‘lov qilmaydi va pochta/yetkazib beruvchi xizmatining to‘lovini qabul paytida to‘lamaydi.", "Mahsulot faqat toza, kiyilmagan, yuvilmagan, shikastlanmagan, yorliq va asl qadoqlari saqlangan holda qabul qilinadi. Qaytariladigan mahsulot SIREN omboriga kelib, tekshiruvdan muvaffaqiyatli o‘tgandan keyingina pul mablag‘i qaytariladi."] },
      { title: "4. Shikastlangan yoki shartga mos bo‘lmagan qaytarma", paragraphs: ["Tekshiruvda mahsulot kiyilgan, yuvilgan, hidlangan, ifloslangan, shikastlangan yoki uning yorlig‘i/qadoqlari yo‘q deb topilsa, qaytarish rad etilishi mumkin. Bunday mahsulot uchun to‘lov ham, yetkazib berish xarajatlari ham qaytarilmaydi, agar amaldagi qonunchilik boshqacha talab qilmasa.", "Mijoz to‘lovi ko‘zda tutilgan jo‘natmani yubormasligi kerak. Bunday jo‘natma qabul qilinmasligi mumkin. Rad etilgan yoki qaytarib olinmagan mahsulot {{STORAGE_PERIOD}} davomida omborda saqlanadi; qayta jo‘natish va saqlash xarajatlari mijoz hisobidan bo‘ladi."] },
      { title: "5. Almashtirish va pulni qaytarish", paragraphs: ["Rang yoki razmerni almashtirish mavjud zaxiraga bog‘liq. Kerakli variant mavjud bo‘lmasa, qaytarish yoki yangi buyurtma varianti taklif qilinadi. Xaridor xohishiga ko‘ra almashtirishda qayta yetkazib berish xarajatini mijoz to‘laydi.", "Qaytarish tasdiqlangach, mablag‘ asl to‘lov usuliga yoki qonunda ruxsat etilgan boshqa tartibda qaytariladi. Muddat: {{REFUND_PERIOD}}."] },
      { title: "6. Draft holati", paragraphs: ["Bu sahifa rebrending va sotuvchi rekvizitlari tayyorlanayotgan davr uchun draftdir. {{LEGAL_ENTITY_NAME}}, {{RETURN_ADDRESS}}, {{STORAGE_PERIOD}} va muddatlar to‘ldirilmaguncha ushbu matn asosida tijorat faoliyatini boshlash tavsiya etilmaydi."] },
    ] },
  },
  ru: {
    delivery: { eyebrow: "ПОКУПАТЕЛЯМ", title: "Доставка и оплата", intro: "Этот документ определяет основной порядок оформления, оплаты и доставки заказов в интернет-магазине SIREN.", updated: "Последнее обновление: {{POLICY_UPDATED_AT}}", sections: [
      { title: "1. Данные продавца", paragraphs: ["Продавец: {{LEGAL_ENTITY_NAME}}. ИНН: {{TAX_ID}}. Юридический адрес: {{LEGAL_ADDRESS}}.", "По вопросам заказов и обращений: {{SUPPORT_EMAIL}}, {{SUPPORT_PHONE}}."] },
      { title: "2. Оформление заказа", paragraphs: ["До подтверждения заказа покупатель видит выбранные товары, скидку и стоимость доставки. Получение уведомления не означает автоматическое подтверждение заказа.", "При технической ошибке цены, наличия или адреса продавец связывается с покупателем для согласования решения."] },
      { title: "3. Оплата", paragraphs: ["Оплата планируется через Payme одной операцией: стоимость товаров и доставки оплачиваются вместе.", "Стоимость доставки рассчитывается на checkout по адресу, объёму заказа и тарифу {{DELIVERY_PROVIDER_NAME}}. До успешного завершения оплаты заказ не считается оплаченным."] },
      { title: "4. Доставка", paragraphs: ["Доставка выполняется через {{DELIVERY_PROVIDER_NAME}}. Территория, ориентировочный срок и цена отображаются при оформлении заказа.", "Покупатель отвечает за корректность контактных данных и адреса. Дополнительные расходы из-за неверного адреса могут быть возложены на покупателя."] },
      { title: "5. Получение и обращения", paragraphs: ["При получении рекомендуем проверить внешнее состояние упаковки. При повреждении или несоответствии товара обратитесь в {{SUPPORT_EMAIL}} с фото или видео."] },
    ] },
    returns: { eyebrow: "ПОКУПАТЕЛЯМ", title: "Обмен и возврат", intro: "Этот документ устанавливает предварительный порядок обмена, возврата и рассмотрения обращений по одежде и аксессуарам.", updated: "Последнее обновление: {{POLICY_UPDATED_AT}}", sections: [
      { title: "1. Как обратиться", paragraphs: ["Срок обращения: {{RETURN_PERIOD}}. Напишите на {{SUPPORT_EMAIL}}, указав номер заказа, товар, описание ситуации и фото/видео.", "Адрес возврата: {{RETURN_ADDRESS}}. До отправки товара получите инструкции от команды SIREN."] },
      { title: "2. Производственный дефект или ошибка комплектации", paragraphs: ["Если SIREN подтвердит производственный дефект, ошибку комплектации или несоответствие заказу, SIREN организует или оплачивает доставку товара обратно на склад. До отправки покупателю необходимо получить инструкцию по возврату.", "После поступления на склад товар проходит проверку. При подтверждении дефекта покупатель может выбрать возврат стоимости товара, обмен либо иной предусмотренный законом вариант. Первоначальная стоимость доставки не возвращается автоматически; однако требование закона или обязанность возместить подтверждённые убытки имеют приоритет."] },
      { title: "3. Возврат по желанию покупателя", paragraphs: ["Если размер, цвет, фасон не подошли или товар не понравился, покупатель самостоятельно и полностью оплачивает доставку возврата. SIREN не оплачивает такие отправления заранее и не принимает посылки с оплатой доставки получателем.", "Товар принимается только в чистом, неиспользованном, нестираном и неповреждённом виде, с ярлыками и оригинальной упаковкой. Деньги возвращаются только после поступления товара на склад SIREN и успешной проверки."] },
      { title: "4. Повреждённый или не соответствующий условиям возврат", paragraphs: ["Если при проверке обнаружены следы носки, стирки, запах, загрязнение, повреждение либо отсутствие ярлыков/упаковки, в возврате может быть отказано. В этом случае стоимость товара и доставки не возвращается, кроме случаев, когда законодательство требует иного.", "Не отправляйте посылки с оплатой получателем: они могут быть не приняты. Отклонённый или невостребованный товар хранится на складе {{STORAGE_PERIOD}}; повторная отправка и хранение оплачиваются покупателем."] },
      { title: "5. Обмен и возврат средств", paragraphs: ["Обмен размера или цвета зависит от наличия. Если нужного варианта нет, может быть предложен возврат или новый заказ. При обмене по желанию покупателя повторную доставку оплачивает покупатель.", "После подтверждения возврата средства возвращаются исходным способом оплаты или иным способом, разрешённым законом. Срок: {{REFUND_PERIOD}}."] },
      { title: "6. Статус draft", paragraphs: ["Это черновик на период ребрендинга и подготовки реквизитов продавца. До заполнения {{LEGAL_ENTITY_NAME}}, {{RETURN_ADDRESS}}, {{STORAGE_PERIOD}} и сроков не рекомендуется запускать коммерческие продажи по этому тексту."] },
    ] },
  },
  en: {
    delivery: { eyebrow: "FOR CUSTOMERS", title: "Delivery and payment", intro: "This document sets out the core process for placing, paying for and delivering SIREN online-store orders.", updated: "Last updated: {{POLICY_UPDATED_AT}}", sections: [
      { title: "1. Seller details", paragraphs: ["Seller: {{LEGAL_ENTITY_NAME}}. Tax ID: {{TAX_ID}}. Registered address: {{LEGAL_ADDRESS}}.", "For order questions and requests, contact {{SUPPORT_EMAIL}} or {{SUPPORT_PHONE}}."] },
      { title: "2. Placing an order", paragraphs: ["Before submitting an order, the customer sees the selected products, discount and delivery price. An order-received notification does not by itself confirm the order.", "If a price, stock or address error is found, the seller contacts the customer to agree on a solution."] },
      { title: "3. Payment", paragraphs: ["Payment is planned through Payme in one transaction: product and delivery costs are paid together.", "Delivery cost is calculated at checkout by the address, order volume and {{DELIVERY_PROVIDER_NAME}} tariff. An order is not considered paid until payment succeeds."] },
      { title: "4. Delivery", paragraphs: ["Delivery is made through {{DELIVERY_PROVIDER_NAME}}. Area, estimated period and price are shown at checkout.", "The customer is responsible for accurate contact and address details. Extra costs caused by an incorrect address may be charged to the customer."] },
      { title: "5. Receiving and claims", paragraphs: ["We recommend checking the package exterior on receipt. For damage or a mismatch, contact {{SUPPORT_EMAIL}} with photo or video evidence."] },
    ] },
    returns: { eyebrow: "FOR CUSTOMERS", title: "Exchanges and returns", intro: "This document sets out the preliminary process for exchanges, returns and claims concerning clothing and accessories.", updated: "Last updated: {{POLICY_UPDATED_AT}}", sections: [
      { title: "1. How to contact us", paragraphs: ["Request period: {{RETURN_PERIOD}}. Email {{SUPPORT_EMAIL}} with the order number, product, description and photo/video.", "Return address: {{RETURN_ADDRESS}}. Obtain instructions from SIREN before sending an item."] },
      { title: "2. Manufacturing defect or fulfilment error", paragraphs: ["If SIREN confirms a manufacturing defect, fulfilment error or order mismatch, SIREN arranges or pays for return delivery to the warehouse. Obtain return instructions before dispatch.", "After receipt, the product is inspected. If the defect is confirmed, the customer may choose a product refund, exchange or another remedy required by law. Original delivery is not automatically refunded where the law does not require it."] },
      { title: "3. Customer-preference returns", paragraphs: ["If a size, colour or style is unsuitable, the customer pays the full return-delivery cost. SIREN does not prepay such shipments or accept collect-on-delivery parcels.", "An item is accepted only if clean, unworn, unwashed and undamaged, with tags and original packaging. Funds are refunded after the item reaches the SIREN warehouse and passes inspection."] },
      { title: "4. Non-compliant return", paragraphs: ["A return may be refused if inspection finds wear, washing, odour, contamination, damage or missing tags/packaging. Product and delivery costs are then not refunded, unless applicable law requires otherwise.", "Do not send collect-on-delivery parcels: they may be refused. Rejected or unclaimed items are stored for {{STORAGE_PERIOD}}; repeat delivery and storage are paid by the customer."] },
      { title: "5. Exchange and refund", paragraphs: ["Size or colour exchanges depend on stock. If the needed option is unavailable, a refund or new order may be offered. Customer-preference exchanges require the customer to pay repeat delivery.", "After a return is approved, funds are returned to the original payment method or another method permitted by law. Period: {{REFUND_PERIOD}}."] },
      { title: "6. Draft status", paragraphs: ["This is a draft while the brand and seller details are being finalised. Commercial sales should not start under this text until the placeholders and periods are completed."] },
    ] },
  },
  ja: {
    delivery: { eyebrow: "お客様へ", title: "配送とお支払い", intro: "本書は、SIRENオンラインストアにおける注文、支払い、配送の基本的な手順を定めるものです。", updated: "最終更新日：{{POLICY_UPDATED_AT}}", sections: [
      { title: "1. 販売者情報", paragraphs: ["販売者：{{LEGAL_ENTITY_NAME}}。納税者番号：{{TAX_ID}}。登記住所：{{LEGAL_ADDRESS}}。", "注文やお問い合わせは、{{SUPPORT_EMAIL}} または {{SUPPORT_PHONE}} までご連絡ください。"] },
      { title: "2. 注文手続き", paragraphs: ["注文送信前に、商品、割引、配送費が表示されます。注文受付の通知のみでは、注文の確定を意味しません。", "価格、在庫、住所に技術的な誤りがある場合、販売者は解決方法についてお客様に連絡します。"] },
      { title: "3. お支払い", paragraphs: ["Paymeによる1回の決済を予定しており、商品代金と配送費をまとめてお支払いいただきます。", "配送費は住所、注文量、{{DELIVERY_PROVIDER_NAME}} の料金に基づき、チェックアウトで計算されます。決済完了前の注文は支払済みとはみなされません。"] },
      { title: "4. 配送", paragraphs: ["配送は {{DELIVERY_PROVIDER_NAME}} を通じて行われます。配送地域、目安の日数、価格はチェックアウトで表示されます。", "お客様は正確な連絡先と住所を入力する責任があります。誤った住所による追加費用はお客様負担となる場合があります。"] },
      { title: "5. 受け取りとお問い合わせ", paragraphs: ["受け取り時には梱包の外観をご確認ください。破損や相違がある場合は、写真または動画を添えて {{SUPPORT_EMAIL}} へご連絡ください。"] },
    ] },
    returns: { eyebrow: "お客様へ", title: "交換・返品", intro: "本書は、衣類およびアクセサリーの交換、返品、申し立てに関する暫定的な手順を定めるものです。", updated: "最終更新日：{{POLICY_UPDATED_AT}}", sections: [
      { title: "1. お問い合わせ方法", paragraphs: ["申請期間：{{RETURN_PERIOD}}。注文番号、商品、状況の説明、写真または動画を添えて {{SUPPORT_EMAIL}} へご連絡ください。", "返品先：{{RETURN_ADDRESS}}。発送前にSIRENチームの案内を受けてください。"] },
      { title: "2. 製造不良または発送ミス", paragraphs: ["製造不良、発送ミス、注文内容との不一致がSIRENにより確認された場合、SIRENは倉庫への返送を手配または負担します。発送前に返品案内を取得してください。", "倉庫到着後に検品を行います。不良が確認された場合、商品代金の返金、交換、または法律で定められた救済を選択できます。法律で必要とされない限り、当初の配送費は自動返金されません。"] },
      { title: "3. お客様都合の返品", paragraphs: ["サイズ、色、デザインが合わない場合は、お客様が返品配送料を全額負担します。SIRENはこのような配送を前払いせず、着払い荷物も受け取りません。", "商品は未使用・未洗濯・無傷で、タグと元の梱包がある場合にのみ受け付けます。SIREN倉庫への到着と検品完了後に返金します。"] },
      { title: "4. 条件を満たさない返品", paragraphs: ["着用、洗濯、におい、汚れ、損傷、タグや梱包の欠落が確認された場合、返品をお断りすることがあります。この場合、法律で別段の定めがない限り商品代金および配送費は返金されません。", "着払いで発送しないでください。受け取りを拒否する場合があります。拒否または未受領の商品は {{STORAGE_PERIOD}} 保管され、再配送および保管費用はお客様負担です。"] },
      { title: "5. 交換と返金", paragraphs: ["サイズまたは色の交換は在庫状況によります。必要な商品がない場合は、返金または新規注文をご案内することがあります。お客様都合の交換の再配送費はお客様負担です。", "返品承認後、返金は元の支払い方法または法律で認められた別の方法で行います。期間：{{REFUND_PERIOD}}。"] },
      { title: "6. 草案の状態", paragraphs: ["本書はブランド変更および販売者情報確定中の草案です。プレースホルダーと期間が入力されるまで、この文書に基づく商用販売を開始しないでください。"] },
    ] },
  },
};

export default function PolicyDocument({ kind }: { kind: Kind }) {
  const { locale } = useLanguage();
  const policy = policies[locale][kind];
  const draftNotice = locale === "ru"
    ? "Пока реквизиты и данные интеграции не заполнены, эта страница не является финальной публичной офертой."
    : locale === "en" ? "Until legal details and integration data are completed, this page is not a final public offer."
      : locale === "ja" ? "販売者情報と連携情報が入力されるまで、このページは最終的な公開オファーではありません。"
        : "Rekvizitlar va integratsiya ma’lumotlari to‘ldirilmaguncha bu sahifa yakuniy ommaviy oferta hisoblanmaydi.";
  return <main className="policy-document"><Link className="profile-settings-back" href="/">← SIREN</Link><header><p>{policy.eyebrow}</p><h1>{policy.title}</h1><span>{policy.intro}</span><small>{policy.updated}</small></header><aside><b>DRAFT — REBRANDING</b><span>{draftNotice}</span></aside><article>{policy.sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>)}</article></main>;
}
