"use client";
import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import FixedTop from "@/components/FixedTop";
import Footer from "@/components/Footer";
import ProductCard from "@/components/ProductCard";
import { ApiCategory, getStorefrontCategories, getStorefrontListing, StorefrontListing, toStorefrontColorCards } from "@/lib/api";

const labels: Record<string, string> = { male: "Male", female: "Female", unisex: "Unisex" };
const split = (value: string | null) => value?.split(",").filter(Boolean) ?? [];
export default function ShopListing({ category }: { category?: string }) {
  const router = useRouter(); const pathname = usePathname(); const current = useSearchParams();
  const [listing, setListing] = useState<StorefrontListing | null>(null); const [categories, setCategories] = useState<ApiCategory[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true);
  const params = useMemo(() => new URLSearchParams(current.toString()), [current]);
  useEffect(() => { if (category) params.set("category", category); else params.delete("category"); let live = true; setLoading(true); Promise.all([getStorefrontListing(params), getStorefrontCategories()]).then(([data, all]) => { if (live) { setListing(data); setCategories(all); } }).catch(() => { if (live) setListing(null); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [category, params]);
  const update = (key: string, value?: string) => { const next = new URLSearchParams(current.toString()); if (category) next.set("category", category); if (!value) next.delete(key); else next.set(key, value); router.replace(`${pathname}${next.size ? `?${next}` : ""}`, { scroll: false }); };
  const toggle = (key: string, value: string) => { const items = split(current.get(key)); update(key, items.includes(value) ? items.filter((item) => item !== value).join(",") : [...items, value].join(",")); };
  const clear = () => router.replace(category ? `/shop/${category}` : "/shop", { scroll: false });
  const cards = listing ? toStorefrontColorCards(listing.products) : [];
  const title = category ? (categories.find((item) => item.slug === category)?.name || category) : "SHOP";
  const active = ["gender", "colors", "sizes", "minPrice", "maxPrice"].flatMap((key) => split(current.get(key)).map((value) => ({ key, value })));
  return <><FixedTop /><main className="siren-shop-listing"><header className="siren-shop-heading"><div><p>SHOP / {category ? "CATEGORY" : "ALL PRODUCTS"}</p><h1>{title}</h1></div></header><nav className="siren-category-tabs" aria-label="Kategoriyalar"><button className={!category ? "is-active" : ""} onClick={() => router.push("/shop")}>BARCHA MAHSULOTLAR</button>{categories.map((item) => <button key={item.id} className={category === item.slug ? "is-active" : ""} onClick={() => router.push(`/shop/${item.slug}`)}>{item.name}</button>)}</nav><div className="siren-listing-toolbar"><b>{listing?.total ?? 0} PRODUCTS</b><button type="button" onClick={() => setOpen(true)}>FILTER & SORT</button></div>{active.length > 0 && <div className="siren-filter-chips">{active.map(({ key, value }) => <button key={`${key}-${value}`} onClick={() => toggle(key, value)}>{labels[value] || value} ×</button>)}<button onClick={clear}>CLEAR ALL</button></div>}<section className={`siren-shop-grid${loading ? " is-loading" : ""}`}>{cards.map((product, index) => <ProductCard key={product.cardId ?? `${product.id}-${index}`} product={product} />)}{!loading && !cards.length && <div className="siren-shop-empty"><b>NO PRODUCTS FOUND.</b><span>Try removing some filters.</span><button onClick={clear}>CLEAR FILTERS</button></div>}</section></main>{open && <FilterDrawer listing={listing} categories={categories} current={current} lockedCategory={category} onClose={() => setOpen(false)} onUpdate={update} onToggle={toggle} onClear={clear} />}<Footer /></>;
}
function FilterDrawer({ listing, categories, current, lockedCategory, onClose, onUpdate, onToggle, onClear }: { listing: StorefrontListing | null; categories: ApiCategory[]; current: ReturnType<typeof useSearchParams>; lockedCategory?: string; onClose: () => void; onUpdate: (key: string, value?: string) => void; onToggle: (key: string, value: string) => void; onClear: () => void }) {
  const [min, setMin] = useState(current.get("minPrice") || ""); const [max, setMax] = useState(current.get("maxPrice") || ""); const selected = (key: string, value: string) => split(current.get(key)).includes(value);
  const options = (title: string, key: string, facets: Array<{ value: string; count: number }>, swatch = false) => <section><h3>{title}</h3>{facets.map((item) => <label key={item.value}><input type="checkbox" checked={selected(key, item.value)} onChange={() => onToggle(key, item.value)} />{swatch && <i style={{ background: item.value }} />}<span>{labels[item.value] || item.value}</span><small>{item.count}</small></label>)}</section>;
  return <div className="siren-filter-backdrop" onMouseDown={onClose}><aside className="siren-filter-drawer" onMouseDown={(event) => event.stopPropagation()}><header><h2>FILTER & SORT</h2><button onClick={onClose}>×</button></header><section><h3>SORT BY</h3><select value={current.get("sort") || "recommended"} onChange={(event) => onUpdate("sort", event.target.value === "recommended" ? undefined : event.target.value)}><option value="recommended">Recommended</option><option value="newest">Newest</option><option value="price-asc">Price: Low to High</option><option value="price-desc">Price: High to Low</option></select></section>{options("GENDER", "gender", listing?.facets.genders ?? [])}{!lockedCategory && <section><h3>CATEGORY</h3>{categories.map((item) => <label key={item.id}><input type="radio" name="category" checked={current.get("category") === item.slug} onChange={() => onUpdate("category", item.slug)} /><span>{item.name}</span></label>)}</section>}{options("COLOR", "colors", listing?.facets.colors ?? [], true)}{options("SIZE", "sizes", listing?.facets.sizes ?? [])}<section><h3>PRICE · {listing?.facets.price.min.toLocaleString()}–{listing?.facets.price.max.toLocaleString()} UZS</h3><div className="siren-price-inputs"><input inputMode="numeric" placeholder="MIN" value={min} onChange={(event) => setMin(event.target.value)} /><input inputMode="numeric" placeholder="MAX" value={max} onChange={(event) => setMax(event.target.value)} /></div><button className="siren-price-apply" onClick={() => { onUpdate("minPrice", min); onUpdate("maxPrice", max); }}>APPLY PRICE</button></section><footer><button onClick={onClear}>CLEAR</button><button onClick={onClose}>SHOW {listing?.total ?? 0} PRODUCTS</button></footer></aside></div>;
}
