"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowLeft, ExternalLink, FilePenLine, Link2, Plus, Settings2, Trash2, Upload } from "lucide-react";
import { Button } from "./ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
type Item = { id: string; label: string; text: string; url: string; iconUrl: string; iconSize: number; isActive: boolean };
type Profile = { title: string; subtitle: string; handle: string };
type Setting = { key: string; value?: { profile?: Partial<Profile>; items?: Item[] } };
type View = "list" | "item" | "profile";
const blank = (): Item => ({ id: crypto.randomUUID(), label: "", text: "", url: "", iconUrl: "", iconSize: 24, isActive: true });

async function request<T>(path: string, token: string, init: RequestInit = {}) { const response = await fetch(`${API}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, ...(init.body instanceof FormData ? {} : { "Content-Type": "application/json" }), ...(init.headers ?? {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || "Saqlab bo‘lmadi."); return body as T; }

export default function SocialLinksManager({ token, onNotice }: { token: string; onNotice: (message: string) => void }) {
  const [profile, setProfile] = useState<Profile>({ title: "", subtitle: "", handle: "" }); const [items, setItems] = useState<Item[]>([]); const [view, setView] = useState<View>("list"); const [draft, setDraft] = useState<Item | null>(null); const [profileDraft, setProfileDraft] = useState<Profile | null>(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const settings = await request<Setting[]>("/admin/content/settings", token); const setting = settings.find((item) => item.key === "social-links"); setProfile({ title: setting?.value?.profile?.title || "", subtitle: setting?.value?.profile?.subtitle || "", handle: setting?.value?.profile?.handle || "" }); setItems(Array.isArray(setting?.value?.items) ? setting!.value!.items! : []); }, [token]);
  useEffect(() => { void load().catch((error: Error) => onNotice(error.message)); }, [load, onNotice]);
  const persist = async (nextProfile = profile, nextItems = items, message = "O‘zgarishlar saqlandi.") => { setSaving(true); try { await request("/admin/content/settings/social-links", token, { method: "PUT", body: JSON.stringify({ value: { profile: nextProfile, items: nextItems } }) }); setProfile(nextProfile); setItems(nextItems); setView("list"); setDraft(null); setProfileDraft(null); onNotice(message); } catch (error) { onNotice(error instanceof Error ? error.message : "Saqlab bo‘lmadi."); } finally { setSaving(false); } };
  const openNew = () => { setDraft(blank()); setView("item"); };
  const openEdit = (item: Item) => { setDraft({ ...item }); setView("item"); };
  const remove = async (item: Item) => { if (!window.confirm(`“${item.label}” havolasi o‘chirilsinmi?`)) return; await persist(profile, items.filter((row) => row.id !== item.id), "Havola o‘chirildi."); };
  const toggle = async (item: Item) => await persist(profile, items.map((row) => row.id === item.id ? { ...row, isActive: !row.isActive } : row), item.isActive ? "Havola o‘chirildi." : "Havola yoqildi.");
  const upload = async (file?: File) => { if (!file || !draft) return; try { const form = new FormData(); form.append("file", file); const result = await request<{ url: string }>("/admin/content/social/upload-icon", token, { method: "POST", body: form }); setDraft({ ...draft, iconUrl: result.url }); onNotice("SVG ikonka yuklandi."); } catch (error) { onNotice(error instanceof Error ? error.message : "SVG yuklanmadi."); } };
  const saveItem = (event: FormEvent) => { event.preventDefault(); if (!draft) return; const exists = items.some((item) => item.id === draft.id); const next = exists ? items.map((item) => item.id === draft.id ? draft : item) : [...items, draft]; void persist(profile, next, exists ? "Havola yangilandi." : "Yangi havola qo‘shildi."); };
  const saveProfile = (event: FormEvent) => { event.preventDefault(); if (profileDraft) void persist(profileDraft, items, "Sahifa sozlamalari saqlandi."); };
  const back = () => { setView("list"); setDraft(null); setProfileDraft(null); };

  if (view === "profile" && profileDraft) return <section className="social-editor"><header className="social-editor__head"><div><button type="button" className="social-editor__back" onClick={back}><ArrowLeft size={16} /> Havolalarga qaytish</button><p className="ui-overline">SOCIAL PAGE / SETTINGS</p><h2>Sahifa sozlamalari</h2><span>Bu matnlar `/social` sahifasining yuqori qismida ko‘rinadi.</span></div><Button form="social-profile-form" disabled={saving}>{saving ? "Saqlanmoqda…" : "Saqlash"}</Button></header><form id="social-profile-form" className="social-editor__form" onSubmit={saveProfile}><Card><CardHeader><div><CardTitle>Profil matnlari</CardTitle><CardDescription>Qisqa va tanish bo‘ladigan matnlar yozing.</CardDescription></div></CardHeader><CardContent><div className="social-editor__grid"><label>Sarlavha<input value={profileDraft.title} onChange={(event) => setProfileDraft({ ...profileDraft, title: event.target.value })} placeholder="BIZ BILAN BOG‘LANING" /></label><label>Handle yoki domen<input value={profileDraft.handle} onChange={(event) => setProfileDraft({ ...profileDraft, handle: event.target.value })} placeholder="@siren yoki siren.uz" /></label><label className="is-wide">Qisqa tavsif<textarea value={profileDraft.subtitle} onChange={(event) => setProfileDraft({ ...profileDraft, subtitle: event.target.value })} placeholder="Yangi drop va yangiliklarni kuzating." /></label></div></CardContent></Card></form></section>;
  if (view === "item" && draft) return <section className="social-editor"><header className="social-editor__head"><div><button type="button" className="social-editor__back" onClick={back}><ArrowLeft size={16} /> Havolalarga qaytish</button><p className="ui-overline">SOCIAL PAGE / LINK</p><h2>{items.some((item) => item.id === draft.id) ? "Havolani tahrirlash" : "Yangi havola"}</h2><span>Kerakli ma’lumotlarni kiriting va faqat tayyor bo‘lganda yoqing.</span></div><Button form="social-link-form" disabled={saving}>{saving ? "Saqlanmoqda…" : "Saqlash"}</Button></header><form id="social-link-form" className="social-editor__form" onSubmit={saveItem}><Card><CardHeader><div><CardTitle>Havola ma’lumotlari</CardTitle><CardDescription>URL majburiy. SVG ikonka ixtiyoriy, lekin sahifani ancha tushunarli qiladi.</CardDescription></div></CardHeader><CardContent><div className="social-editor__grid"><label>Nomi<input required value={draft.label} onChange={(event) => setDraft({ ...draft, label: event.target.value })} placeholder="Instagram" /></label><label>Havola (URL)<input required type="url" value={draft.url} onChange={(event) => setDraft({ ...draft, url: event.target.value })} placeholder="https://instagram.com/..." /></label><label>Qo‘shimcha matn<input value={draft.text} onChange={(event) => setDraft({ ...draft, text: event.target.value })} placeholder="@siren" /></label><label>Ikonka o‘lchami, px<input type="number" min="12" max="64" value={draft.iconSize} onChange={(event) => setDraft({ ...draft, iconSize: Number(event.target.value) || 24 })} /></label></div><div className="social-editor__icon"><div>{draft.iconUrl ? <img src={draft.iconUrl.startsWith("/uploads/") ? `${API.replace(/\/api$/, "")}${draft.iconUrl}` : draft.iconUrl} style={{ width: draft.iconSize, height: draft.iconSize }} alt="" /> : <Link2 size={24} />}</div><span><b>SVG ikonka</b><small>Faqat SVG, maksimal 1 MB.</small></span><label><Upload size={16} /> SVG yuklash<input type="file" accept="image/svg+xml,.svg" onChange={(event) => void upload(event.target.files?.[0])} /></label></div><label className="social-editor__status"><input type="checkbox" checked={draft.isActive} onChange={(event) => setDraft({ ...draft, isActive: event.target.checked })} /><span><b>{draft.isActive ? "Havola yoqilgan" : "Havola o‘chiq"}</b><small>Yoqilganda `/social` sahifasida ko‘rinadi.</small></span></label></CardContent></Card></form></section>;
  return <section className="social-links-index"><header className="social-links-index__head"><div><p className="ui-overline">FOOTER / LINK-IN-BIO</p><h2>Ijtimoiy tarmoqlar</h2><span>Footer’dagi “Ijtimoiy tarmoqlar” tugmasi ochadigan sahifani boshqaring.</span></div><div><a href="/social" target="_blank" rel="noreferrer"><ExternalLink size={16} /> Sahifani ko‘rish</a><Button type="button" onClick={openNew}><Plus size={16} /> Havola qo‘shish</Button></div></header><div className="social-links-index__summary"><button type="button" onClick={() => { setProfileDraft(profile); setView("profile"); }}><Settings2 size={19} /><span><b>Sahifa sozlamalari</b><small>{profile.title || "Sarlavha va tavsifni sozlang"}</small></span><FilePenLine size={17} /></button><div><b>{items.filter((item) => item.isActive).length}</b><span>yoqilgan havola</span></div><div><b>{items.length}</b><span>jami havola</span></div></div><Card className="social-links-index__card"><CardHeader><div><CardTitle>Havolalar</CardTitle><CardDescription>Faqat yoqilgan havolalar mijozlarga ko‘rinadi.</CardDescription></div></CardHeader><CardContent><div className="social-links-index__list">{items.map((item, index) => <article key={item.id}><div className="social-links-index__order">{index + 1}</div><div className="social-links-index__icon">{item.iconUrl ? <img src={item.iconUrl.startsWith("/uploads/") ? `${API.replace(/\/api$/, "")}${item.iconUrl}` : item.iconUrl} style={{ width: item.iconSize, height: item.iconSize }} alt="" /> : <Link2 size={20} />}</div><div className="social-links-index__copy"><b>{item.label || "Nomsiz havola"}</b><small>{item.text || item.url}</small></div><a href={item.url || "#"} target="_blank" rel="noreferrer" aria-label="Havolani ochish"><ExternalLink size={16} /></a><span className={item.isActive ? "is-active" : ""}>{item.isActive ? "Yoqilgan" : "O‘chiq"}</span><div className="social-links-index__actions"><button type="button" onClick={() => void toggle(item)}>{item.isActive ? "O‘chirish" : "Yoqish"}</button><button type="button" onClick={() => openEdit(item)}>Tahrirlash</button><button type="button" aria-label="O‘chirish" onClick={() => void remove(item)}><Trash2 size={16} /></button></div></article>)}{!items.length && <div className="social-links-index__empty"><Link2 size={28} /><b>Hali havola yo‘q</b><span>Birinchi rasmiy ijtimoiy tarmoq havolasini qo‘shing.</span><Button type="button" onClick={openNew}><Plus size={16} /> Havola qo‘shish</Button></div>}</div></CardContent></Card></section>;
}
