import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { IsNull, Not, Repository } from 'typeorm';
import { AuditLog, Order, Partner, PartnerComment, PartnerPromoUsage, PartnerType } from '../database/entities';
export type PartnerInput = { name: string; type: PartnerType; logoUrl?: string | null; showInCheckoutSummary?: boolean; email?: string | null; phone?: string | null; social?: string | null; promoCode?: string | null; discountPercent?: number; productIds?: string[]; note?: string | null };
@Injectable()
export class PartnersService {
  constructor(@InjectRepository(Partner) private partners: Repository<Partner>, @InjectRepository(PartnerPromoUsage) private usages: Repository<PartnerPromoUsage>, @InjectRepository(PartnerComment) private comments: Repository<PartnerComment>, @InjectRepository(Order) private orders: Repository<Order>, @InjectRepository(AuditLog) private audit: Repository<AuditLog>) {}
  async list(archived = false) {
    const partners = await this.partners.find({ where: { archivedAt: archived ? Not(IsNull()) : IsNull() }, order: { createdAt: 'DESC' } });
    const [usages, comments] = await Promise.all([this.usages.find({ select: { partnerId: true } }), this.comments.find({ select: { partnerId: true, body: true, createdAt: true }, order: { createdAt: 'DESC' } })]);
    const usageCount = new Map<string, number>(); const commentCount = new Map<string, number>(); const latestComment = new Map<string, string>();
    usages.forEach((usage) => usageCount.set(usage.partnerId, (usageCount.get(usage.partnerId) ?? 0) + 1));
    comments.forEach((comment) => { commentCount.set(comment.partnerId, (commentCount.get(comment.partnerId) ?? 0) + 1); if (!latestComment.has(comment.partnerId)) latestComment.set(comment.partnerId, comment.body); });
    return partners.map((partner) => ({ ...partner, usageCount: usageCount.get(partner.id) ?? 0, commentCount: commentCount.get(partner.id) ?? 0, latestComment: latestComment.get(partner.id) ?? null }));
  }
  async checkoutPartners() { return (await this.partners.find({ where: { isActive: true, showInCheckoutSummary: true, archivedAt: IsNull() }, order: { createdAt: 'ASC' } })).filter((partner) => Boolean(partner.logoUrl)).map((partner) => ({ id: partner.id, name: partner.name, logoUrl: partner.logoUrl })); }
  async create(input: PartnerInput, actor?: string) { const { note, ...partnerInput } = input; const promo = input.type === PartnerType.INFLUENCER || input.type === PartnerType.REFERRAL ? input.promoCode?.trim().toUpperCase() : null; const saved = await this.partners.save(this.partners.create({ ...partnerInput, showInCheckoutSummary: Boolean(input.showInCheckoutSummary), promoCode: promo || null, discountPercent: promo ? Math.max(1, Math.min(99, Number(input.discountPercent) || 0)) : 0, productIds: input.productIds ?? [], perCustomerLimit: input.type === PartnerType.REFERRAL ? 1 : null })); if (note?.trim()) await this.comments.save(this.comments.create({ partnerId: saved.id, authorId: actor ?? null, body: note.trim() })); await this.audit.save(this.audit.create({ actorId: actor ?? null, action: 'created', entityType: 'partner', entityId: saved.id, payload: { type: saved.type } })); return saved; }
  async setCheckoutSummary(id: string, showInCheckoutSummary: boolean, actor?: string) { const item = await this.partners.preload({ id, showInCheckoutSummary }); if (!item) throw new NotFoundException('Hamkor topilmadi'); const saved = await this.partners.save(item); await this.audit.save(this.audit.create({ actorId: actor ?? null, action: showInCheckoutSummary ? 'checkout_summary_enabled' : 'checkout_summary_disabled', entityType: 'partner', entityId: id, payload: {} })); return saved; }
  async setActive(id: string, isActive: boolean, actor?: string) { const item = await this.partners.preload({ id, isActive }); if (!item) throw new NotFoundException('Hamkor topilmadi'); const saved = await this.partners.save(item); await this.audit.save(this.audit.create({ actorId: actor ?? null, action: isActive ? 'activated' : 'deactivated', entityType: 'partner', entityId: id, payload: {} })); return saved; }
  async archive(id: string, actor?: string) { const item = await this.partners.preload({ id, isActive: false, archivedAt: new Date() }); if (!item) throw new NotFoundException('Hamkor topilmadi'); const saved = await this.partners.save(item); await this.audit.save(this.audit.create({ actorId: actor ?? null, action: 'archived', entityType: 'partner', entityId: id, payload: {} })); return saved; }
  async addComment(id: string, body: string, actor?: string) { const partner = await this.partners.findOneBy({ id }); if (!partner) throw new NotFoundException('Hamkor topilmadi'); const comment = await this.comments.save(this.comments.create({ partnerId: id, authorId: actor ?? null, body: body.trim() })); await this.audit.save(this.audit.create({ actorId: actor ?? null, action: 'commented', entityType: 'partner', entityId: id, payload: {} })); return comment; }
  async details(id: string) { const partner = await this.partners.findOneBy({ id }); if (!partner) throw new NotFoundException('Hamkor topilmadi'); const usages = await this.usages.find({ where: { partnerId: id }, order: { createdAt: 'DESC' } }); const comments = await this.comments.find({ where: { partnerId: id }, order: { createdAt: 'DESC' } }); const orderIds = usages.map((usage) => usage.orderId).filter((orderId): orderId is string => Boolean(orderId)); const orders = orderIds.length ? await this.orders.findByIds(orderIds) : []; return { partner, comments, promo: { uses: usages.length, discount: usages.reduce((sum, usage) => sum + Number(usage.discountAmount), 0), revenue: orders.reduce((sum, order) => sum + Number(order.totalAmount), 0) } }; }
  async stats() { const partners = await this.partners.find({ order: { createdAt: 'DESC' } }); const usages = await this.usages.find(); return { totals: { partners: partners.length, active: partners.filter(p => p.isActive && !p.archivedAt).length, promoCodes: partners.filter(p => p.promoCode).length, uses: usages.length, discount: usages.reduce((s, u) => s + Number(u.discountAmount), 0) }, top: partners.filter(p => p.promoCode).map(p => ({ id: p.id, name: p.name, code: p.promoCode, uses: usages.filter(u => u.partnerId === p.id).length, discount: usages.filter(u => u.partnerId === p.id).reduce((s, u) => s + Number(u.discountAmount), 0) })).sort((a,b) => b.uses-a.uses) }; }
}
