"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import Footer from "@/components/Footer";
import { customerApi, useCustomerAuth } from "@/components/CustomerAuthProvider";
import { useLanguage } from "@/components/LanguageProvider";

type Order = { id: string; orderNumber: string; status: string; fulfillmentStatus?: string; paymentStatus: string; totalAmount: string; discountAmount: string; createdAt: string; shippingAddress?: { fulfillmentMethod?: string }; items: Array<{ id: string; titleSnapshot: string; skuSnapshot?: string | null; quantity: number; totalPrice: string; imageUrl?: string | null }> };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
const image = (url?: string | null) => !url ? "/images/p1.jpg" : url.startsWith("/uploads/") ? `${API.replace(/\/api$/, "")}${url}` : url;
const stage = (order: Order) => order.status === "refunded" || order.paymentStatus === "refunded" ? -2 : order.status === "cancelled" || order.fulfillmentStatus === "pickup_expired" ? -1 : order.fulfillmentStatus === "delivered" || order.status === "delivered" || order.fulfillmentStatus === "picked_up" ? 3 : order.fulfillmentStatus === "shipped" || order.status === "shipped" ? 2 : order.fulfillmentStatus === "processing" || order.status === "processing" ? 1 : 0;

export default function ProfileOrdersPage() {
  const { customer, loading, openAuth } = useCustomerAuth();
  const { locale } = useLanguage();
  const text = (uz: string, ru: string, en: string) => locale === "ru" ? ru : locale === "en" ? en : uz;
  const dateLocale = locale === "ru" ? "ru-RU" : locale === "en" ? "en-GB" : "uz-UZ";
  const money = (value: string) => `${new Intl.NumberFormat(dateLocale, { maximumFractionDigits: 0 }).format(Number(value) || 0)} UZS`;
  const [orders, setOrders] = useState<Order[]>([]); const [ordersLoading, setOrdersLoading] = useState(false);
  useEffect(() => { const token = localStorage.getItem("siren-customer-token"); if (!customer || !token) { setOrders([]); return; } setOrdersLoading(true); void customerApi("/checkout/customer/orders", undefined, token).then(setOrders).catch(() => setOrders([])).finally(() => setOrdersLoading(false)); }, [customer?.id]);
  const statusLabel = (order: Order) => { const value = stage(order); if (value === -2) return text("Pul qaytarildi", "ДЕНЬГИ ВОЗВРАЩЕНЫ", "REFUNDED"); if (value === -1) return text("Bekor qilingan", "ОТМЕНЁН", "CANCELLED"); return order.shippingAddress?.fulfillmentMethod === "pickup" ? [text("Tasdiqlash kutilmoqda", "ОЖИДАЕТ ПОДТВЕРЖДЕНИЯ", "AWAITING CONFIRMATION"), text("Qabul qilindi", "ПРИНЯТ", "ACCEPTED"), text("Olib ketishga tayyor", "ГОТОВ К ВЫДАЧЕ", "READY FOR PICKUP"), text("Olib ketildi", "ПОЛУЧЕН", "COLLECTED")][value] : [text("Qabul qilindi", "ПРИНЯТ", "ACCEPTED"), text("Yig‘ildi", "СОБРАН", "PACKED"), text("Yo‘lda", "В ПУТИ", "ON THE WAY"), text("Yetkazildi", "ДОСТАВЛЕН", "DELIVERED")][value]; };
  return <><main className="profile-orders-page"><Link className="profile-settings-back" href="/profile">← {text("Profilga qaytish", "Вернуться в профиль", "Back to profile")}</Link>{loading ? <p className="profile-empty">{text("Buyurtmalar yuklanmoqda…", "Загрузка заказов…", "Loading orders…")}</p> : !customer ? <section className="profile-settings-auth"><h1>{text("Buyurtmalar", "Заказы", "Orders")}</h1><p>{text("Buyurtmalar tarixini ko‘rish uchun akkauntga kiring.", "Войдите, чтобы посмотреть историю заказов.", "Sign in to view your order history.")}</p><button type="button" onClick={openAuth}>{text("Kirish / ro‘yxatdan o‘tish", "Войти / зарегистрироваться", "Sign in / create account")}</button></section> : <section className="customer-orders customer-orders--history"><header><div><p>{text("BUYURTMALAR", "ЗАКАЗЫ", "ORDERS")}</p><h1>{text("Barcha buyurtmalar", "Все заказы", "All orders")}</h1><span>{text("Faol, muvaffaqiyatli, bekor qilingan va refund buyurtmalar.", "Активные, выполненные, отменённые и возвращённые заказы.", "Active, completed, cancelled and refunded orders.")}</span></div><span>{orders.length} {text("ta", "шт.", "items")}</span></header>{ordersLoading ? <p className="profile-empty">{text("Buyurtmalar yuklanmoqda…", "Загрузка заказов…", "Loading orders…")}</p> : orders.map((order) => { const active = stage(order); return <article className={`customer-order ${active < 0 ? "is-cancelled" : ""}`} key={order.id}><header><div><b>{text("Chek", "Чек", "Order")} #{order.orderNumber}</b><small>{new Intl.DateTimeFormat(dateLocale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(order.createdAt))}</small></div><span className={`customer-order-status stage-${Math.max(0, active)}`}>{statusLabel(order)}</span></header><div className="customer-order-items">{order.items.map((item) => <div key={item.id}><img src={image(item.imageUrl)} alt="" /><span><b>{item.titleSnapshot}</b><small>{item.skuSnapshot || "SKU"} × {item.quantity}</small></span><strong>{money(item.totalPrice)}</strong></div>)}</div><footer>{Number(order.discountAmount) > 0 && <span>{text("Chegirma", "Скидка", "Discount")} −{money(order.discountAmount)}</span>}<b>{text("Jami", "ИТОГО", "TOTAL")}: {money(order.totalAmount)}</b></footer></article>; })}{!ordersLoading && !orders.length && <div className="customer-orders-empty"><b>{text("Buyurtma yo‘q", "ЗАКАЗОВ НЕТ", "NO ORDERS")}</b><span>{text("Barcha buyurtmalaringiz shu yerda ko‘rinadi.", "Все ваши заказы будут показаны здесь.", "All your orders will appear here.")}</span><Link href="/shop">{text("Xarid qilish", "В МАГАЗИН", "SHOP NOW")}</Link></div>}</section>}</main><Footer /></>;
}
