import { MigrationInterface, QueryRunner } from 'typeorm';

/** Additive only: existing users retain their legacy role and continue to work. */
export class CreateTeamRbacFoundation1726290000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS employee_internal_id_seq START 1`);
    await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS team_internal_id_seq START 1`);
    await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS role_internal_id_seq START 1`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS employees (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), employee_id varchar(24) NOT NULL UNIQUE, user_id uuid UNIQUE REFERENCES users(id) ON DELETE SET NULL, first_name varchar(100) NOT NULL DEFAULT '', last_name varchar(100) NOT NULL DEFAULT '', middle_name varchar(100), display_name varchar(160), email varchar(255), phone varchar(40), avatar_url varchar, job_title varchar(160), status varchar(24) NOT NULL DEFAULT 'invited', employment_type varchar(24) NOT NULL DEFAULT 'full_time', birth_date date, residential_address varchar, country varchar(100), region varchar(120), city varchar(120), emergency_contact_name varchar, emergency_contact_phone varchar, manager_employee_id uuid, start_date date, end_date date, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS idx_employees_email_lower ON employees (lower(email)) WHERE email IS NOT NULL`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS teams (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), team_id varchar(24) NOT NULL UNIQUE, name varchar(140) NOT NULL, description text, icon_url varchar, color varchar(20) NOT NULL DEFAULT '#465fff', parent_id uuid REFERENCES teams(id) ON DELETE SET NULL, leader_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL, created_by uuid REFERENCES users(id) ON DELETE SET NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS employee_teams (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE CASCADE, team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE, is_primary boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(employee_id, team_id))`);
    await queryRunner.query(`CREATE UNIQUE INDEX IF NOT EXISTS idx_employee_primary_team ON employee_teams(employee_id) WHERE is_primary`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS admin_roles (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), role_id varchar(24) NOT NULL UNIQUE, name varchar(120) NOT NULL UNIQUE, description text, color varchar(20) NOT NULL DEFAULT '#465fff', is_system boolean NOT NULL DEFAULT false, is_protected boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, created_by uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS permissions (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), key varchar(120) NOT NULL UNIQUE, module varchar(80) NOT NULL, label varchar(160) NOT NULL, is_sensitive boolean NOT NULL DEFAULT false, default_scope varchar(16) NOT NULL DEFAULT 'all')`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS role_permissions (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), role_id uuid NOT NULL REFERENCES admin_roles(id) ON DELETE CASCADE, permission_id uuid NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, scope varchar(16) NOT NULL DEFAULT 'all', UNIQUE(role_id, permission_id))`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS employee_roles (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE CASCADE, role_id uuid NOT NULL REFERENCES admin_roles(id) ON DELETE RESTRICT, assigned_by uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(employee_id, role_id))`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS employee_invitations (id uuid PRIMARY KEY DEFAULT uuid_generate_v4(), token_hash varchar(255) NOT NULL UNIQUE, employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE CASCADE, email varchar(255) NOT NULL, expires_at timestamptz NOT NULL, accepted_at timestamptz, cancelled_at timestamptz, created_by uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now())`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_employee_invitations_active ON employee_invitations(employee_id, expires_at) WHERE accepted_at IS NULL AND cancelled_at IS NULL`);
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS employee_invitations, employee_roles, role_permissions, permissions, admin_roles, employee_teams, teams, employees`);
    await queryRunner.query(`DROP SEQUENCE IF EXISTS role_internal_id_seq, team_internal_id_seq, employee_internal_id_seq`);
  }
}
